### ISSUE TITLE
180th meridian

### ISSUE THREAD

**Issue by RicoZ-OSM** [osmcode/osmcoastline#19]
Hi, noticed the special handling of the coastline of Antarctica - should/could a similar method be employed for Fiji islands such as Taveuni?

At least JOSM has severe problems with coastlines crossing the 180th meridian and it doesn't seem it could be fixed anytime soon:(

http://wiki.openstreetmap.org/wiki/180th_meridian

**Comment by joto** [comment]
Aaaargh. It isn't a good idea to handle special cases by adding special tags or ways. This makes handling actually harder, not simpler. Unfortunately osmcoastline has to handle some of those cases of bad data already, because they were added by people who didn't understand the issues and now they are in the data. I will not add more special handling to osmcoastline. Do not add any bogus data to OSM because it seems to make things simpler. It doesn't.
